# Makefile for SFLib

COMPONENT = SFLib

TARGET = SFLib

OBJS = colpick config dataxfer debug errors event general   \
       heap icons ihelp menus msgs resources saveas stack   \
       strdup string tasks templates url windows

CINCLUDES = -IC:,OSLib:

include CLibrary

# Dynamic dependencies:
